backend:
  image:
    repository: ghcr.io/stardust65613/search
    tag: latest

  nameOverride: search
  fullnameOverride: search
  databaseName: search
  ingress:
    enabled: true
    host: api.staging.yas.local
    path: /search/
  extraEnvFroms:
    - secretRef:
        name: yas-elasticsearch-credentials-secret
  extraVolumes:
    - name: search-application
      configMap:
        name: search-application-configmap
  extraVolumeMounts:
    - name: search-application
      mountPath: /opt/yas/search
  extraApplicationConfigPaths:
    - /opt/yas/search/search-application.yaml

  resources:
    requests:
      cpu: 200m      
      memory: 512Mi   
    limits:
      cpu: 1000m      
      memory: 1Gi

  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 10
    targetCPUUtilizationPercentage: 70