name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    strategy:
      matrix:
        service: [product]

    steps:
      - uses: actions/checkout@v4

      - name: Build Java application
        run: |
          cd common-library
          mvn clean install -DskipTests

          cd ${{ matrix.service }}
          mvn clean package -DskipTests

      # 1. Build và Push Image lên GHCR
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: ./${{ matrix.service }}
          file: ./${{ matrix.service }}/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository }}/${{ matrix.service }}:${{ github.sha }}

      # 2. Cập nhật tag mới vào file values.yaml
      - name: Update Helm values
        run: |
          # Dùng yq để cập nhật tag trong file values.yaml
          # Giả sử file values.yaml của bạn có cấu trúc image.tag: ...
          sed -i "s|tag:.*|tag: ${{ github.sha }}|" k8s/env/dev/product-values.yaml

      # 3. Commit và Push lại file vừa cập nhật
      - name: Commit and Push manifest
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add k8s/env/dev/product-values.yaml
          git commit -m "Update image tag to ${{ github.sha }}"
          git push